[project]
search_path = [".", "backend", "agents"]
python_version = "3.13"
python-interpreter-path = "d:/hackathon/.venv/Scripts/python.exe"
site-package-path = ["d:/hackathon/.venv/Lib/site-packages"]
